
volumes:
  node_modules:

services:
  app:
    build: .
    ports:
      - 127.0.0.1:5173:5173
      - 127.0.0.1:4173:4173
    volumes:
      # Dockerでnode_modulesをホストとコンテナで同期しないようにする
      # https://zenn.dev/tamanugi/articles/6f372d45b85c18
      - node_modules:/app/node_modules
      - ./:/app/:rw
